# Generated by Django 5.1.4 on 2024-12-24 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=100, unique=True)),
                ('user_id', models.CharField(max_length=100)),
                ('transaction_date', models.DateTimeField()),
                ('product_category', models.CharField(max_length=100)),
                ('product_name', models.CharField(max_length=200)),
                ('merchant_name', models.CharField(max_length=200)),
                ('product_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cashback', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('loyalty_points', models.IntegerField(blank=True, null=True)),
                ('payment_method', models.CharField(max_length=50)),
                ('transaction_status', models.CharField(max_length=50)),
                ('merchant_id', models.CharField(blank=True, max_length=100, null=True)),
                ('device_type', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=200)),
            ],
        ),
    ]
